print('Meu primeiro programa em Python')
num1 = int(input('Digite um número: '))
num2 = int(input('Digite outro número: '))
print('O resultado de', num1, '+', num2, ':', num1 + num2)
print('Fim do programa')
