P1 = float(input('Digite o peso da P1: '))
P2 = float(input('Digite o peso da P2: '))
N1 = float(input('Digite a N1: '))
N2 = float(input('Digite a N2: '))
media = ((N1 * P1) + (N2 * P2)) / (P1 + P2)
print('A media ponderada do aluno eh:', media)
input('Aperte enter para sair...')
